name: Check All Jobs Status

on:
  push:
    branches:
      - main

jobs:
  abc:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running abc job"
      - run: exit 0  # Change to 1 to simulate failure

  def:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running def job"
      - run: exit 0  # Change to 1 to simulate failure

  eee:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running eee job"
      - run: exit 0  # Change to 1 to simulate failure

  report:
    runs-on: ubuntu-latest
    needs: [abc, def, eee]
    if: always()
    steps:
      - name: Set and print workflow status
        run: |
          status="${{ 
            (needs.abc.result == 'success' && 
             needs.def.result == 'success' && 
             needs.eee.result == 'success') && 
            'success' || 'failure' 
          }}"
          echo "$status"
          [[ "$status" == "success" ]] || exit 1
