name: Clone, Modify, and Create PR

on:
  push:
    branches:
      - main  # Trigger this workflow on push to the main branch

jobs:
  clone_and_modify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    
    - name: Set up Git configuration
      run: |
        git config --global user.name "venky"
        git config --global user.email "venkyy82@gmail.com"
    
    - name: Create a new branch
      run: |
        NEW_BRANCH="feature/modify-file-$(date +'%Y%m%d%H%M%S')"
        git checkout -b $NEW_BRANCH
        echo "New branch created: $NEW_BRANCH"
    
    - name: Modify a file
      run: |
        echo "This is a modification made by GitHub Actions" >> demo/sample.txt
        git add demo/sample.txt
        git commit -m "Modified demo/sample.txt"
    
    - name: Push the changes to the new branch
      run: |
        git push origin $NEW_BRANCH
