name: Clone, Modify, and Create PR

on:
  push:
    branches:
      - main  # Trigger this workflow on push to the main branch

jobs:
  clone_and_modify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        ref: main  # Ensure we checkout the latest main branch
    
    - name: Set up Git configuration
      run: |
        git config --global user.name "venky"
        git config --global user.email "venkyy82@gmail.com"
    
    - name: List repository files for debugging
      run: |
        echo "Listing files in the repository:"
        ls -al  # List all files in the root directory for debugging
    
    - name: Create a new branch
      run: |
        NEW_BRANCH="feature/modify-file-$(date +'%Y%m%d%H%M%S')"
        git checkout -b $NEW_BRANCH
        echo "New branch created: $NEW_BRANCH"
    
    - name: Modify the file
      run: |
        echo "This is a modification made by GitHub Actions" >> sample.txt
        git add sample.txt
        git commit -m "Modified sample.txt"
    
    - name: Push the changes to the new branch
      run: |
        # Push the new branch to remote and set it to track the remote branch
        git push origin $NEW_BRANCH  # Push without setting the upstream branch separately
    
    - name: Install GitHub CLI
      run: |
        sudo apt-get install gh  # Install the GitHub CLI tool
    
    - name: Authenticate GitHub CLI
      run: |
        gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"  # Login using the GitHub token
    
    - name: Create Pull Request
      run: |
        gh pr create --title "Add new modifications" \
                     --body "This PR includes changes made to sample.txt through GitHub Actions." \
                     --base main \
                     --head $NEW_BRANCH \
                     --assignee ${{ github.actor }} \
                     --label "enhancement"
