name: Testing Workflow

on:
  push:
    branches:
      - main  # You can modify this to any branch you want to trigger the workflow for

jobs:
  print-details:
    runs-on: ubuntu-latest

    steps:
      - name: Print all details
        run: |
          echo "Job Status: ${{ job.status }}"
          echo "Workflow Name: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Repository Name: ${{ github.repository }}"
          echo "Workflow URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
