name: Clone, Modify, and Create PR

on:
  push:
    branches:
      - main  # Trigger this workflow on push to the main branch

jobs:
  clone_and_modify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        ref: main  # Ensure we checkout the latest main branch
    
    - name: Set up Git configuration
      run: |
        git config --global user.name "venky"
        git config --global user.email "venkyy82@gmail.com"
    
    - name: List repository files for debugging
      run: |
        echo "Listing files in the repository:"
        ls -al  # List all files in the root directory for debugging
    
    - name: Create a new branch
      run: |
        NEW_BRANCH="feature/modify-file-$(date +'%Y%m%d%H%M%S')"
        git checkout -b $NEW_BRANCH
        echo "New branch created: $NEW_BRANCH"
    
    - name: Check if the sample.txt file exists
      run: |
        echo "Checking for sample.txt"
        if [ ! -f sample.txt ]; then echo "sample.txt does not exist"; exit 1; fi

    - name: Modify the file
      run: |
        echo "This is a modification made by GitHub Actions" >> sample.txt
        git add sample.txt
        git commit -m "Modified sample.txt"
    
    - name: Check remotes
      run: |
        git remote -v  # Confirm that 'origin' is correctly set

    - name: Authenticate and Push the changes to the new branch
      run: |
        # Authenticate with your custom token (PASSWORD1_TOKEN) for private repo access
        git remote set-url origin https://x-access-token:${{ secrets.PASSWORD1_TOKEN }}@github.com/venkyy8/demo.git
        
        # Ensure the branch is pushed and the upstream is set
        git push --set-upstream origin $NEW_BRANCH  # Explicitly push and set the upstream

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.PASSWORD1_TOKEN }}
        base: main
        head: $NEW_BRANCH
        title: "Automated PR: Modify sample.txt"
        body: "This PR contains modifications made by GitHub Actions."
        draft: false
