name: Print Job Status, Workflow Name, Run ID, and Repository Name

on:
  push:
    branches:
      - main  # You can modify this to any branch you want to trigger the workflow for

jobs:
  print-details:
    runs-on: ubuntu-latest

    steps:
      - name: Print Job Status
        run: |
          echo "Job Status: ${{ job.status }}"
      
      - name: Print Workflow Name
        run: |
          echo "Workflow Name: ${{ github.workflow }}"
      
      - name: Print Run ID
        run: |
          echo "Run ID: ${{ github.run_id }}"

      - name: Print Repository Name
        run: |
          echo "Repository Name: ${{ github.repository }}"
