name: Clone, Modify, and Create PR

on:
  push:
    branches:
      - main  # Trigger this workflow on push to the main branch

jobs:
  clone_and_modify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        ref: main  # Ensure we checkout the latest main branch
        token: ${{ secrets.PASSWORD1_TOKEN }}  # Use your custom token for authentication
    
    - name: Set up Git configuration
      run: |
        git config --global user.name "venky"
        git config --global user.email "venkyy82@gmail.com"
        git config --global push.autoSetupRemote true  # Automatically set upstream on first push
    
    - name: Debug repository state
      run: |
        git status
        git branch -a
        git remote -v
    
    - name: Create a new branch
      run: |
        NEW_BRANCH="feature/modify-file-$(date +'%Y%m%d%H%M%S')"
        git checkout -b $NEW_BRANCH
        echo "New branch created: $NEW_BRANCH"
    
    - name: Modify the file
      run: |
        echo "This is a modification made by GitHub Actions" >> sample.txt
        git add sample.txt
        git commit -m "Modified sample.txt"
    
    - name: Push the changes to the new branch
      run: |
        git push --set-upstream origin $NEW_BRANCH  # Push and set the upstream in one step
    
    - name: Install GitHub CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y gh
        gh --version  # Print the version for debugging
    
    - name: Authenticate GitHub CLI
      run: |
        gh auth login --with-token <<< "${{ secrets.PASSWORD1_TOKEN }}"  # Use your custom token for authentication
    
    - name: Debug branch name
      run: |
        echo "New branch name: $NEW_BRANCH"
    
    - name: Create Pull Request
      run: |
        # Create the pull request with the specified title and description
        PR_URL=$(gh pr create --title "1st-PR" \
                               --body "@yvsr please review and merge" \
                               --base main \
                               --head "$NEW_BRANCH")  # Ensure the branch name is quoted
        
        # Print the PR URL for debugging
        echo "Pull Request URL: $PR_URL"


